services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development 
      DB_HOST: ${DBHOST} # Connect to the PostgreSQL service
      DB_USER: ${DBUSER}
      DB_PASSWORD: ${DBPASSWORD}
      DB_NAME: ${PGDATABASE}
    depends_on:
      - db
volumes:
  postgres_data: